publish.modrinth = "FvEITava"
publish.curseforge = 1585354

loomx.loom_version="1.17-SNAPSHOT"

[mod]
version = "1.0.0"
group = "doonv.entityselectortools"
id = "entityselectortools"
name = "Entity Selector Tools"

[deps]
fabric_loader = "0.19.3"
mixinextras = "0.5.3"
lattice = "2.1.0"

["1.21.10"]
parchment = "2025.10.12"

deps.axiom = "65TQdBZB"

deps.fabric_api = "0.138.4"
deps.yacl = "3.8.2+1.21.10"
deps.modmenu = "16.0.1"

deps.amecs-mc = "1.21.9"
deps.amecs-key-modifiers = "1.0.2"
deps.amecs = "1.6.3"

deps.minecraft = "1.21.10"
mod.mc_title = "1.21.10"
mod.mc_targets = "1.21.10"

["1.21.11"]
parchment = "2025.12.20"

deps.axiom = "DLVQrqv2"

deps.fabric_api = "0.141.4"
deps.yacl = "3.8.2+1.21.11"
deps.modmenu = "17.0.0"

deps.amecs-mc = "1.21.9"
deps.amecs-key-modifiers = "1.0.2"
deps.amecs = "1.6.3"

deps.minecraft = "1.21.11"
mod.mc_title = "1.21.11"
mod.mc_targets = "1.21.11"

["26.1.2"]
deps.fabric_api = "0.154.2"
deps.yacl = "3.9.4+26.1"
deps.modmenu = "18.0.0-alpha.7"

deps.amecs-mc = "26.1.0"
deps.amecs-key-modifiers = "1.0.2"
deps.amecs = "1.6.5"
deps.axiom = "AfA2Emww"

deps.minecraft = "~26.1"
mod.mc_title = "26.1.2"
mod.mc_targets = "26.1 26.1.1 26.1.2"

["26.2"]
deps.fabric_api = "0.154.2"
deps.yacl = "3.9.4+26.2"
deps.modmenu = "20.0.0-beta.3"

deps.amecs-mc = "26.2.0"
deps.amecs-key-modifiers = "1.0.2"
deps.amecs = "1.6.5"
deps.axiom = "QO99kC52"

deps.minecraft = ">=26.2"
mod.mc_title = "26.2"
mod.mc_targets = "26.2"

